[package]
name = "ReactTestingLibrary"
version = "0.0.1"
authors = [

]
content_root = "src"

[dependencies]
LuauPolyfill = "github.com/roblox/luau-polyfill@1"
Promise = "github.com/roblox/roblox-lua-promise@3.3.0"
DomTestingLibrary = { git = "https://github.com/roblox/dom-testing-library-lua.git", rev="main" }
React = "github.com/roblox/roact-alignment@17.0.1-rc.16"
ReactRoblox = "github.com/roblox/roact-alignment@17.0.1-rc.16"
Scheduler = "github.com/roblox/roact-alignment@17.0.1-rc.16"
Shared = "github.com/roblox/roact-alignment@17.0.1-rc.16"
JestGlobals = "github.com/roblox/jest-roblox@3.0.0"

[dev_dependencies]
Jest = "github.com/roblox/jest-roblox@3.0.0"
LuauRegExp = "github.com/Roblox/luau-regexp@0.2.0"

