[package]
name = "ReactTestingLibrary"
version = "0.0.1"
authors = [

]
content_root = "src"

[dependencies]
LuauPolyfill = "github.com/roblox/luau-polyfill@1.0.0"
Promise = "github.com/evaera/roblox-lua-promise@4.0.0"
DomTestingLibrary = { git = "https://github.com/roblox/dom-testing-library-lua.git", rev="main" }
React = "github.com/roblox/roact-alignment@17.0.1-rc.15"
ReactRoblox = "github.com/roblox/roact-alignment@17.0.1-rc.15"
Scheduler = "github.com/roblox/roact-alignment@17.0.1-rc.15"
Shared = "github.com/roblox/roact-alignment@17.0.1-rc.15"
JestGlobals = "github.com/roblox/jest-roblox@3.0.0-alpha"

[dev_dependencies]
Jest = "github.com/roblox/jest-roblox@3.0.0-alpha"
LuauRegExp = "github.com/Roblox/luau-regexp@0.2.0"

