[package]
name = "ReactTestingLibrary"
version = "12.3.3"
authors = [
    "Ignacio Falk <flakolefluk@gmail.com>",
    "Allan Jeremy <dev@allanjeremy.com>",
]
content_root = "src"
files = ["*", "!**/__tests__/**"]

[config]
registry_index = true

[dependencies]
LuauPolyfill = "github.com/roblox/luau-polyfill@1"
Promise = "github.com/roblox/roblox-lua-promise@3.3.0"
DomTestingLibrary = "github.com/roblox/dom-testing-library-lua@8.15.0"
React = "github.com/roblox/roact-alignment@17.0.1-rc.16"
ReactRoblox = "github.com/roblox/roact-alignment@17.0.1-rc.16"
Scheduler = "github.com/roblox/roact-alignment@17.0.1-rc.16"
Shared = "github.com/roblox/roact-alignment@17.0.1-rc.16"
JestGlobals = "github.com/roblox/jest-roblox@3.0.0"

[dev_dependencies]
Jest = "github.com/roblox/jest-roblox@3.0.0"
LuauRegExp = { target = "github.com/Roblox/luau-regexp", version = "0.2.0", package = "RegExp" }
